# Generated by Django 3.2.25 on 2025-02-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_app', '0002_auto_20250217_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='photo',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Main Course', 'Main Course'), ('Snack', 'Snack'), ('Drink', 'Drink'), ('Dessert', 'Dessert')], default='Main Course', max_length=20),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/'),
        ),
    ]
