# Generated by Django 4.2.20 on 2025-03-16 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_app', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['table'], name='qrcode_app__table_i_e38c95_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='qrcode_app__created_83847f_idx'),
        ),
    ]
